### ISSUE TITLE
new README errors

### ISSUE THREAD

**Issue by matmont** [javascript-tutorial/it.javascript.info#136]
Some of the errors founded into the new README.md file:

- "In questa repository viene _puubblica_ la traduzione italiana del tutorial javascript.info."
- "Ci _piacrebbe_ ricevere il tuo contributo nella traduzione e/o revisione degli articoli."
- "Prima di iniziare ti segnalo che esiste anche un Canale Discord _in cui potrai con gli altri contributors_ di quello che riguarda la traduzione e revisione degli articoli. O anche ricevere delle indicazioni su come inziare!"
- "Quando effettui le traduzioni lavora sempre in un branch dedicato, in questo modo manteniamo il branch master il più pulito possibile. Continua a _leggerer_ per maggiori informazioni."
- "Scorri la lista e scegli un articolo non ancora assegnato o tradotto. E' possibile _riconsocere_ gli articoli già assegnati poichè riportano il nome del contributor:"
- "Importante Per lavorare alla traduzione ti chiedo di prendere come riferimento l'articolo _inglse_, che puoi trovare al seguente repository. Il tutorial è in costante aggiornamento, quindi la versione inglese presente nel repository italiano potrebbe non essere _aggioranta_ all'ultima versione!"
- "Se l'articolo _contine_ esercizi, è necessaria anche la loro traduzione."
- "Non è necessario tradurre gli esempi, è sufficiente la traduzione dei commenti. Quindi il contenuto _delgi_ alert, nomi delle funzioni/classi deve rimanere in lingua inglese."

**Comment by longo-andrea** [comment]
Grazie per la segnalazione!
