### ISSUE TITLE
Collegamento non funzionante

### ISSUE THREAD

**Issue by mattiapontonio** [javascript-tutorial/it.javascript.info#178]
Se clicco su _Object references and copying_ da #1 usando [l'app di GitHub per Android](https://github.com/mobile) ottengo una schermata bianca (grigio chiaro per l'esattezza).

![Screenshot_20210121-124835.png](https://user-images.githubusercontent.com/44380480/105347449-33d37080-5be7-11eb-8ebe-5ca6e5be6632.png)

**Comment by pasor1** [comment]
In realtà sull'app non funziona nessun collegamento ai vari articoli del tutorial. E' un limite dell'app in sè che è abbastanza basica e con funzionalità limitate e probabilmente c'e un problema nell'interpretazione degli url interni.
Testando il collegamento via browser e controllando il markdown è tutto corretto :wink:

**Comment by mattiapontonio** [comment]
Ma com'è fatto questo URL?
Non riesco a vedere il codice sui commenti degli altri solo sui miei.

**Comment by mattiapontonio** [comment]
Viene così
https://www.github.com/javascript-tutorial/it.javascript.info/tree/master/1-js%2F04-object-basics%2F02-object-copy

**Comment by pasor1** [comment]
l'url è in questo formato 
`https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/04-object-basics/02-object-copy`
che passa via redirect su 
`https://github.com/javascript-tutorial/it.javascript.info/tree/master/1-js/04-object-basics/02-object-copy`
probabilmente l'app (o la webview dell'app) non gestisce correttamente il redirect... ed aggiornare manualmente tutti gli url non è il caso, per il momento :wink:

**Comment by mattiapontonio** [comment]
Ah ho capito.
Bisognerebbe farli relativi.
Però era comodo il copia e incolla al principio immagino 👍🙂

**Comment by mattiapontonio** [comment]
Non era proprio chiusa questa... Era _rimandata_

**Comment by pasor1** [comment]
E' un problema dell'app, non della issue in se'. Questa issue è stata creata da Iliakan per gestire il progress delle varie traduzioni, ed è presente in tutte le repo nelle varie lingue. In tutte le lingue il formato dell' url è il medesimo, quindi prima di andare a toccarlo sarebbe meglio chiedere a Iliakan stesso, onde evitare che in bot smetta di funzionare.

**Comment by mattiapontonio** [comment]
Queste sono altre valide issues 👍
