### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by longo-andrea** [javascript-tutorial/it.javascript.info#245]
Hi @iliakan 👋 

What do you think about publishing the Italian translation? We have reached almost the 70% of translation, and we also reviewed the first part of the tutorial. Maybe publishing can bring more translators on board 😄

**Comment by iliakan** [comment]
Bellissimo! I'll get down to it ASAP.

**Comment by iliakan** [comment]
Hi,

@longo-andrea sent you a letter with the UI lines.

**Comment by longo-andrea** [comment]
thanks, I'm working on! I'll send you all the translations tomorrow! 👍

**Comment by iliakan** [comment]
The tutorial is published!

🥳  🥂 👍 

Thanks to @longo-andrea, @mean2me, @pasor1 and others who made the Italian tutorial happen!
