### ISSUE TITLE
Broken merges on master branch

### ISSUE THREAD

**Issue by rezyx** [javascript-tutorial/it.javascript.info#38]
Hi, I just noticed that there are broken merges in the following files on master:

1-js/02-first-steps/16-javascript-specials/article.md
1-js/03-code-quality/01-debugging-chrome/article.md
1-js/03-code-quality/02-coding-style/article.
1-js/03-code-quality/03-comments/article.
1-js/05-data-types/01-primitives-methods/1-string-new-property/solution.md
1-js/05-data-types/05-array-methods/11-array-unique/solution.md
1-js/05-data-types/05-array-methods/9-shuffle/solution.md
1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/solution.md
1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/task.md
1-js/09-classes/03-static-properties-methods/article.md
1-js/09-classes/05-extend-natives/article.md
1-js/09-classes/07-mixins/article.md
1-js/11-async/01-callbacks/article.md
1-js/11-async/02-promise-basics/article.md
1-js/11-async/03-promise-chaining/article.md
1-js/11-async/04-promise-error-handling/article.md
1-js/11-async/05-promise-api/article.md
1-js/11-async/06-promisify/article.md
2-ui/1-document/01-browser-environment/article.md
2-ui/1-document/02-dom-nodes/article.md
2-ui/1-document/09-size-and-scroll/article.md
2-ui/99-ui-misc/03-event-loop/article.md

**Comment by longo-andrea** [comment]
Oh thanks, i haven't noticed.
I will fix as soon as I can.
