### ISSUE TITLE
[INFO] FOSS Explorer

### ISSUE THREAD

**Issue by TheJoin95** [javascript-tutorial/it.javascript.info#89]
Ciao!

La vostra repository è stata selezionata dalla nostra redazione per il format "FOSS Explorer" di [Schrodinger Hat](https://www.youtube.com/channel/UC1QLLgrGrPmlaFhS0orykCA), una rubrica del nostro talk show riguardo il software development e il mondo open source italiano, e verrà mostrata nella puntata di Martedì 26 Maggio in diretta sul canale [Twitch](https://www.twitch.tv/schrodinger_hat) e [YouTube](https://www.youtube.com/channel/UC1QLLgrGrPmlaFhS0orykCA) alle ore 13.00.

Il vostro lavoro ci è piaciuto molto e speriamo che questo possa aiutare a fornirvi visibilità ;)
Se per te va bene, la includeremo nella nostra top15 bisettimanale!

A presto!

**Comment by longo-andrea** [comment]
Ciao!
Perdonami per il ritardo nel rispondere 🙌 
Comunque ti ringrazio per il suppoto 😄

**Comment by TheJoin95** [comment]
Figurati! Grazie a te! :)
